In [1]:
#Using TensorFlow like NumPy
#TensorFlow’s API revolves around tensors, which flow from operation to 
#operation—hence the name TensorFlow. A tensor is very similar to a 
#NumPy ndarray: it is usually a multidimensional array, but it 
#can also hold a scalar (a simple value, such as 42). These 
#tensors will be important when we create custom cost functions,
#custom metrics, custom layers, and more, so let’s see how to create
#and manipulate them.
    
    
#Tensors and Operations
#You can create a tensor with tf.constant(). For example, here is a
#tensor representing a matrix with two rows and three columns of floats:

import tensorflow as tf
t = tf.constant([[1., 2., 3.], [4., 5., 6.]]) #matrix
t

Metal device set to: Apple M1 Pro


2023-04-07 14:50:27.612797: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-04-07 14:50:27.612920: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [3]:
#Just like an ndarray, a tf.Tensor has a shape and a data type (dtype):

t.shape, t.dtype

(TensorShape([2, 3]), tf.float32)

In [4]:
#Indexing works much like in NumPy:

t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [5]:
t[..., 1, tf.newaxis] #a list of lists

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [9]:
t[:, 1] #single list

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [10]:
#Most importantly, all sorts of tensor operations are available:

t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [11]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [12]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [13]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [14]:
#Tensors and NumPy
#Tensors play nice with NumPy: you can create a tensor from a NumPy 
#array, and vice versa. You can even apply TensorFlow operations to
#NumPy arrays and NumPy operations to tensors:

import numpy as np

a = np.array([2., 4., 5.])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [15]:
t.numpy() ## or np.array(t)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [16]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [17]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

In [ ]:
#WARNING
#Notice that NumPy uses 64-bit precision by default, while TensorFlow
#uses 32-bit. This is because 32-bit precision is generally more than
#enough for neural networks, plus it runs faster and uses less RAM. So
#when you create a tensor from a NumPy array, make sure to set 
#dtype=tf.float32.

In [18]:
#Type Conversions
#Type conversions can significantly hurt performance, and they can 
#easily go unnoticed when they are done automatically. To avoid this, 
#TensorFlow does not perform any type conversions automatically: it
#just raises an exception if you try to execute an operation on tensors
#with incompatible types. For example, you cannot add a float tensor 
#and an integer tensor, and you cannot even add a 32-bit float and a
#64-bit float:


tf.constant(2.) + tf.constant(42)    

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]

In [19]:
tf.constant(2.) + tf.constant(40., dtype=tf.float64)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]

In [20]:
#This may be a bit annoying at first, but remember that it’s for a good
#cause! And of course you can use tf.cast() when you really need to
#convert types

t2 = tf.constant(40., dtype=tf.float64)
tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

In [21]:
#Variables
#The tf.Tensor values we’ve seen so far are immutable: we cannot modify
#them. This means that we cannot use regular tensors to implement weights
#in a neural network, since they need to be tweaked by backpropagation.
#Plus, other parameters may also need to change over time (e.g., a 
#momentum optimizer keeps track of past gradients). What we need is a
#tf.Variable:

v = tf.Variable([[1., 2., 3.], [4., 5., 6]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [28]:
for epoch in range(1, 5):
    print(epoch)

1
2
3
4
